language: node_js

node_js:
    - 4
    - 6
    - 8
    - 10
    - 'node'

cache:
    directories:
        - node_modules

script:
    - npm test
    - node_modules/.bin/travis-commit-message-checker
