init:
    - git config --global core.autocrlf false

environment:
    matrix:
        # Test widely used, and LTS versions of Node
        - nodejs_version: "4.6"
        - nodejs_version: "6.9"

platform:
    - x86

install:
    - ps: Install-Product node $env:nodejs_version
    - npm install

cache:
    node_modules -> package.json

test_script:
    # Output useful info for debugging
    - node --version && npm --version

    # Run any configured tests / linting tools
    - cmd: npm test

build: off
