init:
    - git config --global core.autocrlf false

environment:
    matrix:
        # Test current stable, and LTS versions of Node
        - nodejs_version: "LTS"
        - nodejs_version: "Stable"

platform:
    - x86

install:
    - ps: Install-Product node $env:nodejs_version
    - npm install

cache:
    node_modules -> package.json

test_script:
    # Output useful info for debugging
    - node --version && npm --version

    # Run any configured tests / linting tools
    - cmd: npm test

    # Check format of commit messages
    - cmd: node_modules/.bin/appveyor-commit-message-checker

build: off
